server:
  port: 8080
spring:
  profiles:
    group:
      default: clients
      test: clients-test
      staging: clients-staging
      prod: clients-prod
  mvc:
    static-path-pattern: /test/**
  main:
    banner-mode: off
  r2dbc:
    writer:
      driver: pool
      protocol: mysql
      host: localhost
      port: 33061
      user: kream
      password: kream
      database: kream
    reader:
      driver: pool
      protocol: mysql
      host: localhost
      port: 33061
      user: kream
      password: kream
      database: kream
  data:
    r2dbc:
      repositories:
        enabled: true
    redis:
      host: localhost
      port: 63792
    mongodb:
      uri: mongodb://kream:kream@localhost:27017/kream?authSource=admin
      database: kream
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:33061/kream?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    user: kream
    password: kream
    locations: classpath:db/migration
  kafka:
    schema:
      registry:
        url: localhost:8081
    bootstrap-servers: localhost:9092
    topic:
      bidding-created: kream.bidding.created
      bidding-completed: kream.bidding.completed
jwt:
  secret-key: hidehidehidehidehidehidehidehidehide
logging:
  level:
    org.springframework.kafka.*: OFF
    org.springframework.kafka.listener.[KafkaMessageListenerContainer$ListenerConsumer]: OFF
    org.apache.kafka.*: OFF
    kafka.*: OFF
    org.apache.zookeeper.*: OFF
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters

client:
  pg:
    url: http://localhost:8080
